apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-frontend
  labels:
    app: casino-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casino-frontend
  template:
    metadata:
      labels:
        app: casino-frontend
    spec:

      containers:
        - name: casino-frontend
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/casino-frontend:latest
          env:
            - name: ESTADISTICAS_HOST
              value: "http://estadisticas-service"
            - name: BONOS_HOST
              value: "http://bonos-service"
            - name: BACKEND_HOST
              value: "http://casino-back"
            - name: APUESTAS_HOST
              value: "http://apuestas-service"

